"""empty message

Revision ID: 99f177d76f81
Revises: 
Create Date: 2019-05-04 18:58:25.044864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f177d76f81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('token', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('registration_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_index(op.f('ix_applicants_email'), 'applicants', ['email'], unique=True)
    op.create_index(op.f('ix_applicants_secure_token'), 'applicants', ['secure_token'], unique=False)
    op.create_index(op.f('ix_applicants_token'), 'applicants', ['token'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_secure_token'), 'countries', ['secure_token'], unique=False)
    op.create_table('applicants_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicants_ids_secure_token'), 'applicants_ids', ['secure_token'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_secure_token'), 'regions', ['secure_token'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_secure_token'), 'districts', ['secure_token'], unique=False)
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wards_secure_token'), 'wards', ['secure_token'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('age', sa.DateTime(), nullable=True),
    sa.Column('profile_pic', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_secure_token'), 'users', ['secure_token'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('approved_applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baby_sitters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baby_sitters_secure_token'), 'baby_sitters', ['secure_token'], unique=False)
    op.create_table('billing_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address_line', sa.String(length=120), nullable=True),
    sa.Column('address_line_1', sa.String(length=120), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('town', sa.String(length=120), nullable=True),
    sa.Column('State', sa.String(length=120), nullable=True),
    sa.Column('zip_code', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_address_secure_token'), 'billing_address', ['secure_token'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('device_size', sa.String(length=64), nullable=True),
    sa.Column('user_browser', sa.String(length=64), nullable=True),
    sa.Column('user_os', sa.String(length=64), nullable=True),
    sa.Column('user_lat', sa.Float(), nullable=True),
    sa.Column('user_lng', sa.Float(), nullable=True),
    sa.Column('user_location', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_secure_token'), 'locations', ['secure_token'], unique=False)
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_secure_token'), 'parents', ['secure_token'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_secure_token'), 'role', ['secure_token'], unique=False)
    op.create_table('baby_sitter_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baby_sitter_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('body', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baby_sitter_id'], ['baby_sitters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baby_sitter_notifications_secure_token'), 'baby_sitter_notifications', ['secure_token'], unique=False)
    op.create_table('baby_sitters_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('baby_sitter_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baby_sitter_id'], ['baby_sitters.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baby_sitters_selections_secure_token'), 'baby_sitters_selections', ['secure_token'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baby_sitter_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baby_sitter_id'], ['baby_sitters.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_secure_token'), 'bookings', ['secure_token'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('secure_token', sa.String(length=128), nullable=True),
    sa.Column('body', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['baby_sitter_notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_secure_token'), 'notifications', ['secure_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_secure_token'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_bookings_secure_token'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_baby_sitters_selections_secure_token'), table_name='baby_sitters_selections')
    op.drop_table('baby_sitters_selections')
    op.drop_index(op.f('ix_baby_sitter_notifications_secure_token'), table_name='baby_sitter_notifications')
    op.drop_table('baby_sitter_notifications')
    op.drop_index(op.f('ix_role_secure_token'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_parents_secure_token'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_locations_secure_token'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_billing_address_secure_token'), table_name='billing_address')
    op.drop_table('billing_address')
    op.drop_index(op.f('ix_baby_sitters_secure_token'), table_name='baby_sitters')
    op.drop_table('baby_sitters')
    op.drop_table('approved_applicants')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_secure_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_wards_secure_token'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_districts_secure_token'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_regions_secure_token'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_applicants_ids_secure_token'), table_name='applicants_ids')
    op.drop_table('applicants_ids')
    op.drop_index(op.f('ix_countries_secure_token'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_applicants_token'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_secure_token'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_email'), table_name='applicants')
    op.drop_table('applicants')
    # ### end Alembic commands ###
